package com.idlerpg.game.core.id

/** Stable runtime-instance identifier generated by a controlled IdFactory. */
data class InstanceId(
    val value: Long
) : Comparable<InstanceId> {

    init {
        require(value > 0L) {
            "InstanceId must be positive: $value"
        }
    }

    override fun compareTo(other: InstanceId): Int = value.compareTo(other.value)

    override fun toString(): String = "instance.$value"
}
